# Dependencies
markdown:             kramdown
highlighter:          rouge

# Permalinks
permalink:            pretty

# Setup
title:                Gexos
tagline:              My personal blog
description:          words on tech, sec and other stuff
url:                  https://gexos.github.io
baseurl:
paginate:             5
name:                 Giorgos Xanthopoulos

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# SEO
twitter:
  username:           TheGexos
  url:                https://twitter.com/TheGexos
social:
  name:               Giorgos Xanthopoulos
  links:
    - https://github.com/gexos

# Custom vars
custom_pages:
  feed:               /atom.xml
github:
    url:              https://github.com/gexos
    repo:             https://github.com/gexos/gexos.github.io
excerpt_separator:    <!--more-->
google_analytics:     UA-70773524-1
hyde_version:         2.1.0
hyde_url:             http://hyde.getpoole.com
hyde_repo:            https://github.com/poole/hyde
show_related_posts:   false
force_https:          true

# Comments
comments:
  use_disqus:         true
  use_googleplus:     false
  disqus_shortname:   gexos
